### ISSUE TITLE
License code is not accepted

### ISSUE THREAD

**Issue by markwylde** [deskpro/deskpro-docker#3]
When installing, either from source or from the official docker image, the DeskPRO Admin Interface setup screen will not accept a generated license key.

# Steps to recreate:
1) Create a fresh docker machine
```bash
docker-machine create --driver virtualbox deskpro
eval $(docker-machine env deskpro)
```

2) Create a new `docker-compose.yml` file in a blank directory
```bash
---
version: '2'
services:
  deskpro:
    image: deskpro/deskpro:apache
    depends_on:
      - mariadb
    environment:
      MYSQL_HOST: mariadb
      MYSQL_USER: deskprouser
      MYSQL_PASSWORD: deskpropassword
      MYSQL_DATABASE: deskprodb
    ports:
      - "80:80"
    volumes:
      - deskpro:/var/www/html
  cron:
    image: deskpro/deskpro:apache
    command: deskpro-docker-cron
    depends_on:
      - deskpro
      - mariadb
    volumes:
      - deskpro:/var/www/html
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mysqlrootpassword
      MYSQL_DATABASE: deskprodb
      MYSQL_USER: deskprouser
      MYSQL_PASSWORD: deskpropassword
volumes:
  deskpro:
```

3) Goto your docker-machine ip (e.g. 192.168.99.100)

4) Enter details as requested then click the `Get a demo license` button

5) Wait until the license is emailed then open the attached text file (or just copy from the email, it doesn't matter neither work)

6) Paste in the key into the big text box at the bottom
<img width="1093" alt="screen shot 2018-01-25 at 11 07 14" src="https://user-images.githubusercontent.com/5929807/35385433-2c8592ba-01c0-11e8-8772-e95a97a3eb88.png">

7) Error:
```text
The license code you entered is invalid. Make sure you copy and paste the code exactly as you got it. (Error code: generic) 
```

I have tried on both Chrome and Firefox, but here are my versions anyway:

Chrome: Version 63.0.3239.132 (Official Build) (64-bit)
Firefox: 57.0.4 (64-bit)
Docker: version 17.12.0-ce, build c97c6d6
Docker-Compose: version 1.18.0, build 8dd22a9
Docker-Machine: version 0.13.0, build 9ba6da9
OS: macOS High Sierra 10.13.2
VirtualBox: Version 5.2.4 r119785 (Qt5.6.3)

**Comment by fcoelho** [comment]
Hi Mark, I'm checking what could have happened and will get back to you soon

**Comment by fcoelho** [comment]
@markwylde can you please get me the output of this command? (from the folder where your docker-compose.yml file is)

```
docker-compose exec deskpro cat /var/www/html/app/run/build-num.txt
```

**Comment by markwylde** [comment]
I have run the command `docker-compose exec deskpro cat /var/www/html/app/run/build-num.txt` and the output is below:

```bash
➜  deskpro-docker-hub docker-compose exec deskpro cat /var/www/html/app/run/build-num.txt
31909%                                                                                                                                                                                                ➜  deskpro-docker-hub
```

**Comment by fcoelho** [comment]
I've just tested using a demo license and didn't have any issues, but pushed a new version of the images to the Docker Hub just now.

Can you try re-downloading them (and clearing the volume)? You can run the following to remove the current images and volumes:

```
docker-compose down -v --rmi all
```

**Comment by markwylde** [comment]
I deleted the docker-machine and created a brand new one, but have the exact same problem. Did you use the `Get a demo license` button on the install page?

I recorded the exact steps I took to see if that helps. It's in the video below.

At the end you can see I tried to look at the logs. Unfortunatly there was no `error.log` file this time. When I tried yesterday it contained:
```bash
root@2f819d1d0904:/var/www/html/var/logs# cat server-php.log
[24-Jan-2018 14:20:01 UTC] <DP_LOG:151680360169FAF5> DeskPRO Exception: Error:0 (/app/src/Application/LegacyApiBundle/Controller/SettingsController.php line 500): Class 'Application\LegacyApiBundle\Form\CustomField\Type\PersonStartType' not found
[24-Jan-2018 14:20:27 UTC] <DP_LOG:15168036272A5897> DeskPRO Exception: Error:0 (/app/src/Application/LegacyApiBundle/Controller/SettingsController.php line 500): Class 'Application\LegacyApiBundle\Form\CustomField\Type\PersonStartType' not found
[24-Jan-2018 14:22:03 UTC] <DP_LOG:1516803723C7A496> DeskPRO Exception: Error:0 (/app/src/Application/LegacyApiBundle/Controller/SettingsController.php line 500): Class 'Application\LegacyApiBundle\Form\CustomField\Type\PersonStartType' not found
[24-Jan-2018 14:22:50 UTC] <DP_LOG:1516803770415895> DeskPRO Exception: Error:0 (/app/src/Application/LegacyApiBundle/Controller/SettingsController.php line 500): Class 'Application\LegacyApiBundle\Form\CustomField\Type\PersonStartType' not found
[24-Jan-2018 14:22:57 UTC] <DP_LOG:151680377784D277> DeskPRO Exception: Error:0 (/app/src/Application/LegacyApiBundle/Controller/SettingsController.php line 500): Class 'Application\LegacyApiBundle\Form\CustomField\Type\PersonStartType' not found
[24-Jan-2018 14:23:25 UTC] <DP_LOG:1516803805706CC3> DeskPRO Exception: Error:0 (/app/src/Application/LegacyApiBundle/Controller/SettingsController.php line 500): Class 'Application\LegacyApiBundle\Form\CustomField\Type\PersonStartType' not found
[24-Jan-2018 14:25:02 UTC] <DP_LOG:1516803902965311> DeskPRO Exception: Error:0 (/app/src/Application/LegacyApiBundle/Controller/SettingsController.php line 500): Class 'Application\LegacyApiBundle\Form\CustomField\Type\PersonStartType' not found
```

I will tried installing it on a digitalocean droplet to see if it's maybe a macOS+virtualBox problem.

[![Issue Video Demo](https://img.youtube.com/vi/trdpLkWIFjo/0.jpg)](https://www.youtube.com/watch?v=trdpLkWIFjo)

**Comment by markwylde** [comment]
So I have just tried the same on digital ocean using a CoreOS image and am getting the exact same problem.

Again I have uploaded a video for your reference:

[![Issue Video Demo - Digital Ocean](https://img.youtube.com/vi/6jPo2huKp7c/0.jpg)](https://www.youtube.com/watch?v=6jPo2huKp7c)

**Comment by markwylde** [comment]
So I have good news (for you, not for deskpro) but it appears this probably isn't an issue with `deskpro-docker` so this should maybe be moved into the main deskpro repository.

I installed a new deskpro instance using the [deskpro virtual machine](https://support.deskpro.com/en/downloads/files/deskpro-virtual-machine) image and am getting the same issue. It seems like it's an issue with the demo keys being provided.

**Comment by markwylde** [comment]
I can confirm the issue seems to be fixed. I have just successfully started a new docker-machine with the docker-compose from the README.md file. I requested a new key, and this one has worked.

Thanks for your time investigating this.

**Comment by fcoelho** [comment]
@markwylde I'm sorry it took so long to figure it out, but the issue here was that the key is tied to the machine from which you requested it. The key was probably valid, but for another machine.

If you have any other issues feel free to open another issue here or with support.deskpro.com

**Comment by chrispadfield** [comment]
Just to clarify here, the license code is tied to the database of the Deskpro install that the key was generated for; not the machine the software is installed in.
